model:
  pretrained_checkpoint: checkpoints/dynamicrafter_512_v1/model.ckpt
  resume_checkpoint: ''
  finetune: 2
  base_learning_rate: 1.0e-5
  scale_lr: False
  target: lvdm.models.ddpm3d.LatentVisualAudioDiffusion
  params:
    rescale_betas_zero_snr: True
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: caption
    audio_cond_key: audio
    cond_stage_trainable: False
    image_proj_model_trainable: True
    conditioning_key: hybrid
    image_size: [40, 64]
    channels: 4
    scale_by_std: False
    scale_factor: 0.18215
    use_ema: False
    uncond_prob: 0.05
    uncond_type: 'empty_seq'
    rand_cond_frame: False
    use_dynamic_rescale: True
    base_scale: 0.7
    # fps_condition_type: 'kfidx'
    # fps_condition_type: 'kfs'
    fps_condition_type: 'fps'
    perframe_ae: True
    select_keyframe: False
    use_qformer: False

    unet_config:
      target: lvdm.modules.networks.openaimodel3d_v4.UNetModel
      params:
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        dropout: 0.1
        num_head_channels: 64
        transformer_depth: 1
        context_dim: 1024
        use_linear: true
        use_checkpoint: True
        temporal_conv: True
        use_swin_block: False
        temporal_attention: True
        temporal_selfatt_only: true
        use_relative_position: False
        use_causal_attention: False
        temporal_length: 12
        addition_attention: true
        image_cross_attention: true
        audio_cross_attention: true
        audio_cross_attention_scale_learnable: true
        default_fs: 10
        fs_condition: True
        # add_audio_condition: False

    first_stage_config:
      target: lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        freeze: true
        layer: "penultimate"

    img_cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        freeze: true
    
    image_proj_stage_config:
      target: lvdm.modules.encoders.resampler.Resampler
      params:
        dim: 1024
        depth: 4
        dim_head: 64
        heads: 12
        num_queries: 16
        embedding_dim: 1280
        output_dim: 1024
        ff_mult: 4
        video_length: 12

    audio_proj_stage_config:
      target: lvdm.modules.encoders.resampler.AudioResampler
      params:
        dim: 1024
        depth: 4
        dim_head: 64
        heads: 12
        num_queries: 12
        embedding_dim: 768
        output_dim: 1024
        ff_mult: 4
        video_length: 12
data:
  target: utils_data.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
    wrap: false
    shuffle_val_dataloader: True
    train:
      target: lvdm.data.theGreatestHits.TheGreatestHits
      params:
        data_dir: /dockerx/local/data/TheGreatestHits/videos
        keyframe_dir: /dockerx/local/data/TheGreatestHits/train_video_motion/label/
        filename_list: /dockerx/local/data/TheGreatestHits/train.txt
        video_length: 12
        frame_stride: 1
        fixed_fps: 6
        load_raw_resolution: true
        resolution: [320, 512]
        spatial_transform: resize_center_crop
        random_fs: false  ## if true, we uniformly sample fs with max_fs=frame_stride (above)
        keyframe_ratio: 0.0
    validation:
      target: lvdm.data.theGreatestHits.TheGreatestHits
      params:
        data_dir: /dockerx/local/data/TheGreatestHits/videos
        keyframe_dir: /dockerx/local/data/TheGreatestHits/test_video_motion/label/  
        filename_list: /dockerx/local/data/TheGreatestHits/test.txt
        video_length: 12
        frame_stride: 6
        load_raw_resolution: true
        resolution: [320, 512]
        spatial_transform: resize_center_crop
        random_fs: false  ## if true, we uniformly sample fs with max_fs=frame_stride (above)
